# Generated by Django 4.2.20 on 2026-04-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOZP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_ozp_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('table_dwh', models.CharField(max_length=255)),
                ('example_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subdivision_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroupOZP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_group_ozp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoreGroupERP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_store_sub', models.CharField(max_length=255, unique=True)),
                ('store_name', models.CharField(max_length=255)),
                ('group_ozp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefEditor.groupozp')),
                ('sub_group_ozp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefEditor.subgroupozp')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RefEditor.subdivision')),
            ],
        ),
    ]
