# Generated by Django 4.2.20 on 2026-04-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RefEditor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreGroupERP',
            new_name='StoreGroupOZP',
        ),
        migrations.RenameField(
            model_name='subgroupozp',
            old_name='sub_group_ozp',
            new_name='sub_group_ozp_name',
        ),
    ]
