# Generated by Django 4.2.20 on 2026-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RefEditor', '0002_rename_storegrouperp_storegroupozp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='example_file',
            field=models.FileField(null=True, upload_to='excel'),
        ),
    ]
