# Generated by Django 4.2.20 on 2026-09-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindPurch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PGGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planning_group', models.CharField(max_length=255)),
                ('planning_sales', models.CharField(max_length=255)),
                ('group_goods', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('exw_usd', models.FloatField()),
                ('ddp_usd', models.FloatField()),
                ('kddp', models.FloatField()),
                ('stock_cnt_day', models.IntegerField()),
                ('percent_stock_end', models.FloatField()),
                ('kind_purch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_purch.kindpurch')),
            ],
        ),
    ]
