# Generated by Django 4.2.20 on 2026-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pggoods',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pggoods',
            name='purch',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
