# Generated by Django 4.2.20 on 2026-09-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0002_pggoods_brand_pggoods_purch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lag_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchPay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('percent_pay', models.FloatField()),
                ('lag_day_pay', models.IntegerField()),
                ('purch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_purch.purch')),
            ],
        ),
    ]
