# Generated by Django 4.2.20 on 2026-09-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0003_purch_purchpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_start_plan', models.DateField()),
                ('date_end_plan', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioPlanSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('flag_order_in_purch', models.BooleanField()),
                ('scenario_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_purch.scenariomodel')),
            ],
        ),
    ]
