# Generated by Django 4.2.20 on 2026-09-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0005_pggoods_scenario_plan_purch_scenario_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariomodel',
            options={'verbose_name': 'Сценарий', 'verbose_name_plural': 'Сценарии'},
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='overwrite_existing',
            field=models.BooleanField(default=False, help_text='Если включено, при сохранении сценария существующие закупки и товары будут обновлены данными из MS SQL. Если выключено — будут добавлены только новые записи.', verbose_name='Перезаписывать существующие данные'),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='date_end_plan',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='date_start_plan',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
