# Generated by Django 4.2.20 on 2026-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0006_alter_scenariomodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCalc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_step', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
