# Generated by Django 4.2.20 on 2026-09-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0007_resultcalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало выполнения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='running', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Порядок выполнения')),
                ('name', models.CharField(max_length=255, verbose_name='Название шага')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало выполнения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('algorithm_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='model_purch.algorithmrun')),
            ],
            options={
                'verbose_name': 'Шаг алгоритма',
                'verbose_name_plural': 'Шаги алгоритма',
                'ordering': ['order'],
            },
        ),
    ]
