# Generated by Django 4.2.20 on 2026-09-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0008_algorithmrun_algorithmstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindLagPay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='purch',
            name='lage_make',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchpay',
            name='kind_lag_pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_purch.kindlagpay'),
        ),
    ]
