# Generated by Django 5.2.18 on 2026-10-07 12:36

import hashlib
import unicodedata
from collections import defaultdict

from django.db import migrations, models


def normalize_and_archive(apps, schema_editor):
    Goods = apps.get_model('model_purch', 'PGGoods')
    Archive = apps.get_model('model_purch', 'PGGoodsDuplicateArchive')
    alias = schema_editor.connection.alias
    groups = defaultdict(list)
    for row in Goods.objects.using(alias).order_by('id').values():
        normalized = unicodedata.normalize('NFC', row['planning_group'].strip()).casefold()
        key = hashlib.sha256(normalized.encode('utf-8')).hexdigest()
        groups[(row['scenario_plan_id'], key)].append(row)
    for (_, key), rows in groups.items():
        kept = rows[-1]  # User-selected policy: highest ID wins, without mixing attributes.
        if len(rows) > 1:
            for row in rows:
                Archive.objects.using(alias).create(
                    original_id=row['id'], scenario_id=row['scenario_plan_id'],
                    kept_id=kept['id'], original_data=row,
                )
            Goods.objects.using(alias).filter(id__in=[row['id'] for row in rows[:-1]]).delete()
        Goods.objects.using(alias).filter(pk=kept['id']).update(planning_group_key=key)


def restore_archived_rows(apps, schema_editor):
    Goods = apps.get_model('model_purch', 'PGGoods')
    Archive = apps.get_model('model_purch', 'PGGoodsDuplicateArchive')
    alias = schema_editor.connection.alias
    for archived in Archive.objects.using(alias).order_by('id'):
        row = dict(archived.original_data)
        pk = row.pop('id')
        # Preserve edits made after migration; only recreate removed rows.
        Goods.objects.using(alias).get_or_create(pk=pk, defaults=row)


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0009_kindlagpay_purch_lage_make_purchpay_kind_lag_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGGoodsDuplicateArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField()),
                ('scenario_id', models.PositiveIntegerField(null=True)),
                ('kept_id', models.PositiveIntegerField()),
                ('original_data', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Архив дублей PGGoods',
                'verbose_name_plural': 'Архив дублей PGGoods',
            },
        ),
        migrations.AddField(
            model_name='pggoods',
            name='planning_group_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.RunPython(normalize_and_archive, restore_archived_rows),
        migrations.AddConstraint(
            model_name='pggoods',
            constraint=models.UniqueConstraint(fields=('scenario_plan', 'planning_group_key'), name='unique_pg_scenario_group'),
        ),
        migrations.AddConstraint(
            model_name='pggoods',
            constraint=models.UniqueConstraint(condition=models.Q(('scenario_plan__isnull', True)), fields=('planning_group_key',), name='unique_pg_unassigned_group'),
        ),
    ]
