# Generated by Django 5.2.18 on 2026-10-07 13:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0010_pggoodsduplicatearchive_pggoods_planning_group_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_container', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за контейнер')),
                ('volume_per_container', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Объём контейнера, м³')),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freight', to='model_purch.scenariomodel', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Фрахт',
                'verbose_name_plural': 'Фрахт по сценариям',
                'constraints': [models.CheckConstraint(condition=models.Q(('price_per_container__gte', 0)), name='freight_price_nonnegative'), models.CheckConstraint(condition=models.Q(('volume_per_container__gt', 0)), name='freight_volume_positive')],
            },
        ),
    ]
