# Generated by Django 5.2.18 on 2026-10-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0011_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmrun',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='algorithmrun',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithm_runs', to='model_purch.scenariomodel'),
        ),
        migrations.CreateModel(
            name='ScenarioExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('parameters', models.JSONField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='model_purch.scenariomodel')),
            ],
            options={
                'verbose_name': 'Экспорт сценария',
                'verbose_name_plural': 'История экспорта сценариев',
                'ordering': ['-exported_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='algorithmrun',
            name='scenario_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_purch.scenarioexport'),
        ),
    ]
