# Generated by Django 5.2.18 on 2026-10-08 09:49

import hashlib
import unicodedata
from django.db import migrations, models


def consolidate(apps, schema_editor):
    alias = schema_editor.connection.alias
    Purch = apps.get_model('model_purch', 'Purch')
    Pay = apps.get_model('model_purch', 'PurchPay')
    Archive = apps.get_model('model_purch', 'PurchScenarioArchive')
    winners = {}
    for data in Purch.objects.using(alias).order_by('-pk').values():
        name = (data['name'] or '').strip()
        key = hashlib.sha256(unicodedata.normalize('NFC', name).casefold().encode('utf-8')).hexdigest()
        kept_id = winners.setdefault(key, data['id'])
        original = {field: value for field, value in data.items() if field != 'name_key'}
        Archive.objects.using(alias).create(original_id=data['id'], kept_id=kept_id,
            original_data=original, payments=list(Pay.objects.using(alias).filter(purch_id=data['id']).order_by('pk').values()))
        if kept_id == data['id']:
            Purch.objects.using(alias).filter(pk=kept_id).update(name=name, name_key=key)
        else:
            Pay.objects.using(alias).filter(purch_id=data['id']).delete()
            Purch.objects.using(alias).filter(pk=data['id']).delete()


def restore(apps, schema_editor):
    alias = schema_editor.connection.alias
    Purch = apps.get_model('model_purch', 'Purch')
    Pay = apps.get_model('model_purch', 'PurchPay')
    Archive = apps.get_model('model_purch', 'PurchScenarioArchive')
    for archive in Archive.objects.using(alias).order_by('original_id'):
        data = dict(archive.original_data)
        original_id = data.pop('id')
        Purch.objects.using(alias).update_or_create(pk=original_id, defaults=data)
        Pay.objects.using(alias).filter(purch_id=original_id).delete()
        for payment in archive.payments:
            Pay.objects.using(alias).create(**payment)



class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0012_algorithmrun_parameters_algorithmrun_scenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchScenarioArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField()),
                ('kept_id', models.PositiveIntegerField()),
                ('original_data', models.JSONField()),
                ('payments', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Архив сценарных закупок',
                'verbose_name_plural': 'Архив сценарных закупок',
            },
        ),
        migrations.AddField(
            model_name='purch', name='name_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.RunPython(consolidate, restore),
        migrations.RemoveField(model_name='purch', name='scenario_plan'),
        migrations.AlterField(
            model_name='purch', name='name_key',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
