# Generated by Django 5.2.18 on 2026-10-08 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0013_purchscenarioarchive_remove_purch_scenario_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pggoods',
            name='container_volume',
            field=models.FloatField(default=65, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Объём контейнера, м³'),
        ),
    ]
