# Generated by Django 5.2.18 on 2026-10-08 20:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0014_pggoods_container_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='volume_per_container',
            field=models.DecimalField(decimal_places=3, default=65, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Архивный объём контейнера, м³'),
        ),
    ]
