# Generated by Django 5.2.18 on 2026-10-08 20:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0015_alter_freight_volume_per_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='customs_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Таможенная ставка, %'),
        ),
        migrations.AddField(
            model_name='freight',
            name='warehouse_delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость доставки до склада'),
        ),
        migrations.AddConstraint(
            model_name='freight',
            constraint=models.CheckConstraint(condition=models.Q(('customs_rate__gte', 0), ('customs_rate__lte', 100)), name='freight_customs_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='freight',
            constraint=models.CheckConstraint(condition=models.Q(('warehouse_delivery_cost__gte', 0)), name='freight_delivery_nonnegative'),
        ),
    ]
