# Generated by Django 5.2.18 on 2026-10-08 20:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0016_freight_customs_rate_freight_warehouse_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pggoods',
            name='duty_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Пошлина, %'),
        ),
        migrations.AddConstraint(
            model_name='pggoods',
            constraint=models.CheckConstraint(condition=models.Q(('duty_rate__gte', 0), ('duty_rate__lte', 100)), name='pggoods_duty_rate_range'),
        ),
    ]
