# Generated by Django 5.2.18 on 2026-10-08 20:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0017_pggoods_duty_rate_pggoods_pggoods_duty_rate_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='pggoods',
            name='cif_usd',
            field=models.FloatField(default=0, editable=False, verbose_name='CIF'),
        ),
        migrations.AddField(
            model_name='pggoods',
            name='customs_payment_usd',
            field=models.FloatField(default=0, editable=False, verbose_name='Таможенный платёж'),
        ),
        migrations.AddField(
            model_name='pggoods',
            name='freight_usd',
            field=models.FloatField(default=0, editable=False, verbose_name='Фрахт за товар'),
        ),
        migrations.AddField(
            model_name='pggoods',
            name='warehouse_delivery_usd',
            field=models.FloatField(default=0, editable=False, verbose_name='Доставка за товар'),
        ),
        migrations.AddField(
            model_name='purch',
            name='is_russian',
            field=models.BooleanField(default=False, verbose_name='Поставщик РФ'),
        ),
        migrations.AlterField(
            model_name='pggoods',
            name='ddp_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pggoods',
            name='kddp',
            field=models.FloatField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Группа товаров')),
                ('name_key', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('duty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Пошлина, %')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duty_rate__gte', 0), ('duty_rate__lte', 100)), name='goods_group_duty_range')],
            },
        ),
    ]
