# Generated by Django 5.2.18 on 2026-10-09 13:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0019_seed_goods_groups_and_calculate_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='foreign_delivery_cost',
            field=models.DecimalField(decimal_places=2, default=1100, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Заграничная доставка без DDP, USD за контейнер'),
        ),
        migrations.AddConstraint(
            model_name='freight',
            constraint=models.CheckConstraint(condition=models.Q(('foreign_delivery_cost__gte', 0)), name='freight_foreign_delivery_nonnegative'),
        ),
    ]
