# Generated by Django 5.2.18 on 2026-10-09 13:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def preserve_supply_types(apps, schema_editor):
    Purch = apps.get_model('model_purch', 'Purch')
    Purch.objects.using(schema_editor.connection.alias).filter(is_russian=True).update(supply_type='russian')


def restore_russian_flags(apps, schema_editor):
    Purch = apps.get_model('model_purch', 'Purch')
    Purch.objects.using(schema_editor.connection.alias).filter(supply_type='russian').update(is_russian=True)


def populate_product_expenses(apps, schema_editor):
    import unicodedata
    alias = schema_editor.connection.alias
    Freight = apps.get_model('model_purch', 'Freight')
    Purch = apps.get_model('model_purch', 'Purch')
    Goods = apps.get_model('model_purch', 'PGGoods')
    normalize = lambda value: unicodedata.normalize('NFC', value or '').strip().casefold()
    freights = {row.scenario_id: row for row in Freight.objects.using(alias).all()}
    suppliers = {normalize(row.name): row.supply_type for row in Purch.objects.using(alias).all()}
    batch = []
    for good in Goods.objects.using(alias).iterator(chunk_size=500):
        freight = freights.get(good.scenario_plan_id)
        if freight and good.container_volume and good.container_volume > 0:
            good.foreign_delivery_usd = float(freight.foreign_delivery_cost) * good.volume / good.container_volume
            good.nr_customs_vat_usd = float(freight.nr_customs_vat_rate) / 100 * good.customs_payment_usd if suppliers.get(normalize(good.purch)) == 'p2' else 0
            batch.append(good)
        if len(batch) == 500:
            Goods.objects.using(alias).bulk_update(batch, ['foreign_delivery_usd', 'nr_customs_vat_usd'])
            batch = []
    if batch:
        Goods.objects.using(alias).bulk_update(batch, ['foreign_delivery_usd', 'nr_customs_vat_usd'])


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0020_freight_foreign_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='nr_customs_vat_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='НР_Таможенный НДС, %'),
        ),
        migrations.AddField(
            model_name='pggoods',
            name='foreign_delivery_usd',
            field=models.FloatField(default=0, editable=False, verbose_name='Расходы на загран доставку без DDP за товар'),
        ),
        migrations.AddField(
            model_name='pggoods',
            name='nr_customs_vat_usd',
            field=models.FloatField(default=0, editable=False, verbose_name='НР_Таможенный НДС за товар'),
        ),
        migrations.AddField(
            model_name='purch',
            name='supply_type',
            field=models.CharField(choices=[('direct', 'Прямой контракт'), ('p2', 'P2'), ('russian', 'Закупка РФ')], default='p2', max_length=16, verbose_name='Тип поставки'),
        ),
        migrations.RunPython(preserve_supply_types, restore_russian_flags),
        migrations.RemoveField(
            model_name='purch',
            name='is_russian',
        ),
        migrations.AddConstraint(
            model_name='freight',
            constraint=models.CheckConstraint(condition=models.Q(('nr_customs_vat_rate__gte', 0), ('nr_customs_vat_rate__lte', 100)), name='freight_nr_vat_rate_range'),
        ),
        migrations.RunPython(populate_product_expenses, migrations.RunPython.noop),
    ]
