# Generated by Django 5.2.18 on 2026-10-09 13:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0021_remove_purch_is_russian_freight_nr_customs_vat_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='foreign_delivery_cost',
            field=models.DecimalField(decimal_places=2, default=1100, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Расходы на загран доставку без DDP, USD за контейнер'),
        ),
    ]
