# Generated by Django 5.2.18 on 2026-10-09 16:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_purch', '0023_zero_russian_purchase_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsgroup',
            name='container_volume',
            field=models.DecimalField(decimal_places=3, default=65, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Объём контейнера, м³'),
        ),
        migrations.AddConstraint(
            model_name='goodsgroup',
            constraint=models.CheckConstraint(condition=models.Q(('container_volume__gte', Decimal('0.001'))), name='goods_group_container_positive'),
        ),
    ]
