# Generated by Django 4.2.20 on 2026-08-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chanel_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_key', models.CharField(max_length=255, unique=True)),
                ('planning_group_sales', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segment_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subdivision_key', models.CharField(max_length=255, unique=True)),
                ('subdivision_name', models.CharField(max_length=255)),
                ('subdivision_global', models.CharField(max_length=255)),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.chanel')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_coeff_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VariationCalculate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variation_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubdivisionCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivation_coeff', models.FloatField()),
                ('manager_coeff', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.goods')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.segmentcoeff')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.subdivision')),
                ('type_coeff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.typecoeff')),
                ('variation_calculate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.variationcalculate')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivation_coeff', models.FloatField()),
                ('manager_coeff', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.goods')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.segmentcoeff')),
                ('type_coeff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.typecoeff')),
                ('variation_calculate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.variationcalculate')),
            ],
        ),
    ]
