# Generated by Django 4.2.20 on 2026-08-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_motivation', '0002_brand_groupgoods_planninggroupsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdivisionManagerCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coeff', models.FloatField()),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.subdivision')),
            ],
        ),
    ]
