# Generated by Django 4.2.20 on 2026-08-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_motivation', '0003_subdivisionmanagercoeff'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindManagerCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterApplyCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quarter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YearMotivation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='subdivisionmanagercoeff',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_motivation.kindmanagercoeff'),
        ),
    ]
