# Generated by Django 4.2.20 on 2026-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_motivation', '0004_kindmanagercoeff_quarterapplycoeff_yearmotivation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='excel')),
            ],
        ),
    ]
