# Generated by Django 5.2.18 on 2026-10-08 13:09

import django.db.models.deletion
from datetime import date
from django.db import migrations, models


def initial_version(apps, schema_editor):
    alias = schema_editor.connection.alias
    Version = apps.get_model('admin_motivation', 'GlobalCoeffVersion')
    Coeff = apps.get_model('admin_motivation', 'GlobalCoeff')
    version = Version.objects.using(alias).create(effective_from=date(2001, 1, 1), title='Исходная версия')
    Coeff.objects.using(alias).update(version_id=version.pk)


def reverse_initial(apps, schema_editor):
    apps.get_model('admin_motivation', 'GlobalCoeff').objects.using(schema_editor.connection.alias).update(version_id=None)



class Migration(migrations.Migration):

    dependencies = [
        ('admin_motivation', '0005_examplefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCoeffVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(unique=True, verbose_name='Дата начала действия')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Версия общих коэффициентов',
                'verbose_name_plural': 'Версии общих коэффициентов',
                'ordering': ['effective_from', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='globalcoeff',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.goods'),
        ),
        migrations.AlterField(
            model_name='globalcoeff',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.segmentcoeff'),
        ),
        migrations.AlterField(
            model_name='globalcoeff',
            name='type_coeff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.typecoeff'),
        ),
        migrations.AlterField(
            model_name='globalcoeff',
            name='variation_calculate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.variationcalculate'),
        ),
        migrations.AddField(
            model_name='globalcoeff',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coefficients', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.RunPython(initial_version, reverse_initial),
        migrations.AlterField(
            model_name='globalcoeff', name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coefficients', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.AddConstraint(
            model_name='globalcoeff',
            constraint=models.UniqueConstraint(fields=('version', 'goods', 'type_coeff', 'segment'), name='unique_global_coeff_version_cell'),
        ),
    ]
