# Generated by Django 5.2.18 on 2026-10-08 14:08

import django.db.models.deletion
from django.db import migrations, models


def share_versions(apps, schema_editor):
    alias = schema_editor.connection.alias
    Version = apps.get_model('admin_motivation', 'GlobalCoeffVersion')
    versions = list(Version.objects.using(alias).order_by('effective_from'))
    first = versions[0]
    for model_name in ['SubdivisionCoeff', 'SubdivisionManagerCoeff']:
        Model = apps.get_model('admin_motivation', model_name)
        Model.objects.using(alias).update(version_id=first.pk)
        original = list(Model.objects.using(alias).values())
        for version in versions[1:]:
            Model.objects.using(alias).bulk_create([
                Model(**{**{key: value for key, value in row.items() if key != 'id'}, 'version_id': version.pk})
                for row in original
            ])


def reverse_share(apps, schema_editor):
    alias = schema_editor.connection.alias
    first = apps.get_model('admin_motivation', 'GlobalCoeffVersion').objects.using(alias).order_by('effective_from').first()
    if first is None:
        return
    for model_name in ['SubdivisionCoeff', 'SubdivisionManagerCoeff']:
        Model = apps.get_model('admin_motivation', model_name)
        Model.objects.using(alias).exclude(version_id=first.pk).delete()
        Model.objects.using(alias).update(version_id=None)



class Migration(migrations.Migration):

    dependencies = [
        ('admin_motivation', '0006_globalcoeffversion_alter_globalcoeff_goods_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalcoeffversion',
            options={'ordering': ['effective_from', 'pk'], 'verbose_name': 'Версия коэффициентов мотивации', 'verbose_name_plural': 'Версии коэффициентов мотивации'},
        ),
        migrations.AddField(
            model_name='subdivisioncoeff',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdivision_coefficients', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.AddField(
            model_name='subdivisionmanagercoeff',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_coefficients', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.AlterField(
            model_name='subdivisioncoeff',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.goods'),
        ),
        migrations.AlterField(
            model_name='subdivisioncoeff',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.segmentcoeff'),
        ),
        migrations.AlterField(
            model_name='subdivisioncoeff',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.subdivision'),
        ),
        migrations.AlterField(
            model_name='subdivisioncoeff',
            name='type_coeff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.typecoeff'),
        ),
        migrations.AlterField(
            model_name='subdivisioncoeff',
            name='variation_calculate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.variationcalculate'),
        ),
        migrations.AlterField(
            model_name='subdivisionmanagercoeff',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.kindmanagercoeff'),
        ),
        migrations.AlterField(
            model_name='subdivisionmanagercoeff',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.subdivision'),
        ),
        migrations.RunPython(share_versions, reverse_share),
        migrations.AlterField(
            model_name='subdivisioncoeff', name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdivision_coefficients', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.AlterField(
            model_name='subdivisionmanagercoeff', name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_coefficients', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.AddConstraint(
            model_name='subdivisioncoeff',
            constraint=models.UniqueConstraint(fields=('version', 'subdivision', 'goods', 'type_coeff', 'segment'), name='unique_sub_coeff_version_cell'),
        ),
        migrations.AddConstraint(
            model_name='subdivisionmanagercoeff',
            constraint=models.UniqueConstraint(fields=('version', 'subdivision', 'kind'), name='unique_manager_coeff_version_kind'),
        ),
    ]
