# Generated by Django 5.2.18 on 2026-10-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_motivation', '0007_alter_globalcoeffversion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlanScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сценария')),
                ('source_version', models.CharField(max_length=255, verbose_name='Версия плана в MS SQL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='Дата плана')),
                ('subdivision', models.CharField(max_length=255)),
                ('planning_group_sales', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=24)),
                ('segment_amounts', models.JSONField(default=dict)),
                ('calculation', models.JSONField(default=dict)),
                ('policies_usd', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('sales_usd', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('total_usd', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('coefficient_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.globalcoeffversion')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='admin_motivation.salesplanscenario')),
            ],
            options={
                'ordering': ['plan_date', 'subdivision', 'planning_group_sales', 'group', 'brand'],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'plan_date', 'subdivision', 'planning_group_sales', 'group', 'brand'), name='unique_motivation_sales_plan_line')],
            },
        ),
    ]
