# Generated by Django 5.2.18 on 2026-10-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_motivation', '0008_salesplanscenario_salesplanline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replaced_ids', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='globalcoeffversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Утверждена'),
        ),
        migrations.AddField(
            model_name='globalcoeffversion',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_versions', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.AddField(
            model_name='globalcoeffversion',
            name='revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalcoeffversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждена'), ('superseded', 'Заменена')], default='draft', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='globalcoeffversion',
            name='effective_from',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
        migrations.AddConstraint(
            model_name='globalcoeffversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('effective_from',), name='unique_approved_motivation_start'),
        ),
        migrations.AddField(
            model_name='motivationapproval',
            name='baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_approvals', to='admin_motivation.globalcoeffversion'),
        ),
        migrations.AddField(
            model_name='motivationapproval',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_motivation.salesplanscenario'),
        ),
        migrations.AddField(
            model_name='motivationapproval',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='admin_motivation.globalcoeffversion'),
        ),
    ]
