"""Compatibility namespace for the active purchase views."""
from ..views import (
    get_current_scenario,
    scenario_list,
    scenario_create,
    scenario_edit,
    scenario_delete,
    pggoods_list,
    edit_pggoods,
    delete_pggoods,
    bulk_update_pggoods,
    export_to_excel,
    import_from_excel,
    purch_list,
    purch_create,
    purch_edit,
    purch_delete,
    copy_pggoods_from_scenario,
    export_scenario_to_sql,
    sync_purch_data,
    sync_pggoods_data_for_scenario,
    results_page,
    start_algorithm_api,
    execute_next_step_api,
    get_algorithm_status_api,
)
