# Generated by Django 4.2.20 on 2026-04-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrangRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chanel_key', models.CharField(max_length=255)),
                ('chanel_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupENRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_EN_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupERPRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_ERP_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OptionPlanRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_key', models.CharField(max_length=255)),
                ('option_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningGroupRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planning_group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningGroupSalesRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planning_group_sales_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subdivision_key', models.CharField(max_length=255)),
                ('subdivision_name', models.CharField(max_length=255)),
                ('chanel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.planninggroupsalesref')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_key', models.CharField(max_length=255)),
                ('type_goods', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.brangref')),
                ('group_EN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.groupenref')),
                ('group_ERP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.grouperpref')),
                ('planning_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.planninggroupref')),
                ('planning_group_sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.planninggroupsalesref')),
            ],
        ),
    ]
