# Generated by Django 4.2.20 on 2026-04-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodPlanRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perion_plan_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Subdivision',
            new_name='SubdivisionRef',
        ),
        migrations.RenameModel(
            old_name='Chanel',
            new_name='ChanelRef',
        ),
        migrations.CreateModel(
            name='PlanSalesByChanelHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='')),
                ('opition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.optionplanref')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSalesByChanelGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
                ('date_plan', models.DateField()),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.chanelref')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.goodsref')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.plansalesbychanelheader')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.periodplanref')),
            ],
        ),
        migrations.CreateModel(
            name='PercentSubdivision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.optionplanref')),
            ],
        ),
    ]
