# Generated by Django 4.2.20 on 2026-04-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0002_periodplanref_rename_subdivision_subdivisionref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansalesbychanelheader',
            name='sheet_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdivisionref',
            name='chanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.chanelref'),
        ),
    ]
