# Generated by Django 4.2.20 on 2026-04-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0003_plansalesbychanelheader_sheet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansalesbychanelheader',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.periodplanref'),
        ),
    ]
