# Generated by Django 4.2.20 on 2026-04-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0004_plansalesbychanelheader_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanelGlobal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chanel_global_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='plansalesbychanelgoods',
            name='amount_ddp_usd',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansalesbychanelgoods',
            name='amount_usd',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsref',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='chanelref',
            name='chanel_global',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.chanelglobal'),
        ),
    ]
