# Generated by Django 4.2.20 on 2026-04-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0005_chanelglobal_plansalesbychanelgoods_amount_ddp_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGoodsRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_goods_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='goodsref',
            name='type_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.typegoodsref'),
        ),
    ]
