# Generated by Django 4.2.20 on 2026-04-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0006_typegoodsref_alter_goodsref_type_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdivisionGlobalRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subdivision_global_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='subdivisionref',
            name='chanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.chanelglobal'),
        ),
        migrations.AddField(
            model_name='subdivisionref',
            name='subdivision_global',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.subdivisionglobalref'),
        ),
    ]
