# Generated by Django 4.2.20 on 2026-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0007_subdivisionglobalref_alter_subdivisionref_chanel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansalesbychanelheader',
            name='year',
            field=models.IntegerField(default=2026, null=True),
        ),
    ]
