# Generated by Django 4.2.20 on 2026-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0008_plansalesbychanelheader_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanelref',
            name='is_subdivision',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
