# Generated by Django 4.2.20 on 2026-04-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0009_chanelref_is_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecentSubdivisionGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.chanelref')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.goodsref')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.plansalesbychanelheader')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.subdivisionref')),
            ],
        ),
        migrations.CreateModel(
            name='PercentSubdivisionHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='')),
                ('sheet_name', models.CharField(default='', max_length=255, null=True)),
                ('year', models.IntegerField(default=2026, null=True)),
                ('opition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.optionplanref')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.periodplanref')),
            ],
        ),
        migrations.DeleteModel(
            name='PercentSubdivision',
        ),
    ]
