# Generated by Django 4.2.20 on 2026-04-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0010_pecentsubdivisiongoods_percentsubdivisionheader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecentsubdivisiongoods',
            old_name='qty',
            new_name='percent',
        ),
    ]
