# Generated by Django 4.2.20 on 2026-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0011_rename_qty_pecentsubdivisiongoods_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatesFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.AlterField(
            model_name='percentsubdivisionheader',
            name='file',
            field=models.FileField(null=True, upload_to='excel'),
        ),
        migrations.AlterField(
            model_name='plansalesbychanelheader',
            name='file',
            field=models.FileField(null=True, upload_to='excel'),
        ),
    ]
