# Generated by Django 4.2.20 on 2026-04-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0012_templatesfile_alter_percentsubdivisionheader_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentSubdivisionSeason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='excel')),
                ('sheet_name', models.CharField(default='', max_length=255, null=True)),
                ('year', models.IntegerField(default=2026, null=True)),
                ('opition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.optionplanref')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.periodplanref')),
            ],
        ),
    ]
