# Generated by Django 5.2.18 on 2026-10-07 09:07

import django.db.models.deletion
from django.db import migrations, models


def remap_headers(apps, schema_editor, source_name, target_name):
    alias = schema_editor.connection.alias
    goods = apps.get_model('PlanningSystem', 'PecentSubdivisionGoods')
    source = apps.get_model('PlanningSystem', source_name)
    target = apps.get_model('PlanningSystem', target_name)
    # Snapshot IDs before changing any FK: new IDs may overlap old header IDs.
    rows = list(goods.objects.using(alias).values_list('pk', 'header_id'))
    mapping = {}
    for _, header_id in rows:
        if header_id not in mapping:
            old = source.objects.using(alias).get(pk=header_id)
            new = target.objects.using(alias).create(
                opition_plan_id=old.opition_plan_id, file=old.file.name,
                sheet_name=old.sheet_name, period_id=old.period_id, year=old.year,
            )
            mapping[header_id] = new.pk
    for pk, header_id in rows:
        goods.objects.using(alias).filter(pk=pk).update(header_id=mapping[header_id])


def forwards(apps, schema_editor):
    remap_headers(apps, schema_editor, 'PlanSalesByChanelHeader', 'PercentSubdivisionHeader')


def backwards(apps, schema_editor):
    remap_headers(apps, schema_editor, 'PercentSubdivisionHeader', 'PlanSalesByChanelHeader')


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningSystem', '0013_percentsubdivisionseason'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='pecentsubdivisiongoods',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanningSystem.percentsubdivisionheader'),
        ),
    ]
